/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What needs doing, the membership in four figures, and the latest log entries. */
        get: operations["admin_dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in person, what they may see, and the counts for their menus. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether somebody is signed in, and the CSRF token for changes. */
        get: operations["session_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /** At */
            at: string;
            /** Category */
            category: string;
            /** Event Type */
            event_type: string;
            /** Id */
            id: number;
            /** Target */
            target: string | null;
        };
        /**
         * Attention
         * @description ``None`` for a kind the person may not act on, so the page does not offer it.
         */
        Attention: {
            /** Health Problems */
            health_problems: string[] | null;
            name_changes: components["schemas"]["Waiting"] | null;
            pictures: components["schemas"]["Waiting"] | null;
            sync_problems: components["schemas"]["Waiting"] | null;
        };
        /**
         * Counts
         * @description Numbers shown beside menu entries; 0 when there is nothing, or nothing the person may see.
         */
        Counts: {
            /** Reviews Waiting */
            reviews_waiting: number;
        };
        /** DashboardOut */
        DashboardOut: {
            attention: components["schemas"]["Attention"];
            /** Figures */
            figures: components["schemas"]["Figure"][];
            /** Recent Activity */
            recent_activity: components["schemas"]["Activity"][] | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /**
             * Details
             * @default null
             */
            details: {
                [key: string]: unknown;
            } | null;
            /**
             * Fields
             * @default null
             */
            fields: {
                [key: string]: string;
            } | null;
            /** Message */
            message: string;
        };
        /** ErrorOut */
        ErrorOut: {
            error: components["schemas"]["ErrorBody"];
        };
        /** Figure */
        Figure: {
            /**
             * Key
             * @enum {string}
             */
            key: "active" | "cancelled" | "forum" | "archive";
            /** Label */
            label: string;
            /** Link Url */
            link_url: string | null;
            /** Note */
            note: string;
            /** Value */
            value: number;
        };
        /** MeOut */
        MeOut: {
            /** Admin Area */
            admin_area: boolean;
            /** Admin Notices */
            admin_notices: components["schemas"]["Notice"][];
            counts: components["schemas"]["Counts"];
            /** Email */
            email: string;
            /** First Name */
            first_name: string | null;
            /** Forum Username */
            forum_username: string | null;
            /** Id */
            id: number;
            /** Last Name */
            last_name: string | null;
            /** Permissions */
            permissions: ("accounts.billing" | "accounts.privacy" | "accounts.view" | "admin.access" | "approvals.review" | "forum.admin" | "forum.moderate" | "forum.moderator" | "logs.view" | "notifications.manage" | "notifications.receive" | "roles.manage" | "settings.credentials" | "settings.general" | "system.backup" | "system.update" | "teams.manage" | "teams.money")[];
            /** Roles */
            roles: string[];
            team_labels: components["schemas"]["TeamLabels"];
            /** Teams Area */
            teams_area: boolean;
        };
        /**
         * Notice
         * @description A banner over every page of an area, for something that is off on purpose or by accident.
         */
        Notice: {
            /**
             * Link Label
             * @default null
             */
            link_label: string | null;
            /**
             * Link Url
             * @default null
             */
            link_url: string | null;
            /** Message */
            message: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "info" | "warning" | "danger";
        };
        /** SessionOut */
        SessionOut: {
            /** Csrf Token */
            csrf_token: string;
            /** Signed In */
            signed_in: boolean;
        };
        /**
         * TeamLabels
         * @description What teams are called here; an admin can rename them.
         */
        TeamLabels: {
            /** Plural */
            plural: string;
            /** Singular */
            singular: string;
        };
        /**
         * Waiting
         * @description How many of one kind wait, and the oldest of them (for sync problems: the latest) in a few words.
         */
        Waiting: {
            /** At */
            at: string | null;
            /** Count */
            count: number;
            /** Summary */
            summary: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    session_state: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
}
