/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One page of the account list, with how many each membership filter would show. */
        get: operations["admin_accounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One account: profile, membership, forum, teams, access, recent activity, and what may be done. */
        get: operations["admin_account"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{user_id}/billing-sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Stripe about this member's subscription and repair what a missed webhook left behind. */
        post: operations["admin_account_billing_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{user_id}/disabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Switch the account off -- no signing in, no forum -- or back on. The membership is left as it is. */
        put: operations["admin_account_disabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{user_id}/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Correct the private address of a member locked out by a wrong one. A confirmation link goes there. */
        put: operations["admin_account_email"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{user_id}/erase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Erase the account's personal data, keeping the payment record. Cannot be undone. */
        post: operations["admin_account_erase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{user_id}/erasure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What erasing the account's personal data would do. Asks Stripe, so it is read only when wanted. */
        get: operations["admin_account_erasure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{user_id}/forum-resync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bring the forum in line with this account now. */
        post: operations["admin_account_forum_resync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{user_id}/old-forum-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Old forum accounts nobody has claimed, to reconnect this account to by hand. */
        get: operations["admin_account_old_forum_candidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{user_id}/picture-replacement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Allow the member one new profile picture, or withdraw that. */
        put: operations["admin_account_picture_replacement"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{user_id}/reconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconnect this account to an old forum account, for a member the address check did not find. */
        post: operations["admin_account_reconnect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{user_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the account's roles to exactly these. */
        put: operations["admin_account_roles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What needs doing, the membership in four figures, and the latest log entries. */
        get: operations["admin_dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What waits for this person's decision, oldest first, and the forum sync problems. */
        get: operations["admin_reviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Past decisions this person could have made, newest first. */
        get: operations["admin_reviews_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews/name-changes/{request_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a change request: the member's record takes the requested details. */
        post: operations["admin_review_change_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews/name-changes/{request_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn a change request down; the member is told, with the note. */
        post: operations["admin_review_change_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews/pictures/{submission_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a profile picture and send it to the forum. */
        post: operations["admin_review_picture_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews/pictures/{submission_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a profile picture; the member is asked for another. */
        post: operations["admin_review_picture_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in person, what they may see, and the counts for their menus. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether somebody is signed in, and the CSRF token for changes. */
        get: operations["session_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Access
         * @description Roles and switching the account off -- for whoever manages access.
         */
        Access: {
            /** Disable Blockers */
            disable_blockers: string[];
            /** Effective Permissions */
            effective_permissions: string[];
            /** Options */
            options: components["schemas"]["RoleOption"][];
            /** Removal Warning */
            removal_warning: string | null;
            /** Roles Locked */
            roles_locked: string | null;
        };
        /** AccountActivity */
        AccountActivity: {
            /** Actor */
            actor: string | null;
            /** After */
            after: unknown;
            /** At */
            at: string;
            /** Before */
            before: unknown;
            /** Category */
            category: string;
            /** Details */
            details: unknown;
            /** Event Type */
            event_type: string;
            /** Id */
            id: number;
        };
        /** AccountListOut */
        AccountListOut: {
            /** Items */
            items: components["schemas"]["AccountRow"][];
            membership_counts: components["schemas"]["MembershipCounts"];
            /** Page */
            page: number;
            /** Pages */
            pages: number;
            /** Per Page */
            per_page: number;
            /** Role Choices */
            role_choices: components["schemas"]["Role"][];
            /** Total */
            total: number;
        };
        /** AccountListQuery */
        AccountListQuery: {
            /**
             * Account
             * @default all
             * @enum {string}
             */
            account?: "all" | "active" | "no_sign_in" | "disabled" | "erased";
            /**
             * Dir
             * @default asc
             * @enum {string}
             */
            dir?: "asc" | "desc";
            /**
             * Kind
             * @description "archived": carried over from the old forum and not reconnected yet.
             * @default all
             * @enum {string}
             */
            kind?: "all" | "portal" | "archived";
            /**
             * Membership
             * @default all
             * @enum {string}
             */
            membership?: "all" | "active" | "ending" | "pending" | "failed" | "ended" | "none";
            /**
             * Page
             * @default 1
             */
            page?: number;
            /**
             * Q
             * @description Name, address or forum username; part of one is enough.
             * @default
             */
            q?: string;
            /**
             * Role
             * @description "all", "staff" (any admin role), "none" (no role) or a role's slug.
             * @default all
             */
            role?: string;
            /**
             * Sort
             * @default name
             * @enum {string}
             */
            sort?: "name" | "kind" | "membership" | "until" | "forum";
        };
        /** AccountOut */
        AccountOut: {
            access: components["schemas"]["Access"] | null;
            /**
             * Account State
             * @enum {string}
             */
            account_state: "active" | "no_sign_in" | "disabled" | "erased";
            actions: components["schemas"]["Actions"];
            /** Disabled At */
            disabled_at: string | null;
            /** Disabled Reason */
            disabled_reason: string | null;
            /** Email */
            email: string;
            /** Email Verified */
            email_verified: boolean;
            /** Erased At */
            erased_at: string | null;
            forum: components["schemas"]["Forum"];
            /** Forum Username */
            forum_username: string | null;
            /** Id */
            id: number;
            membership: components["schemas"]["Membership"] | null;
            /** Name */
            name: string | null;
            old_forum: components["schemas"]["OldForum"] | null;
            /** Recent Activity */
            recent_activity: components["schemas"]["AccountActivity"][];
            /** Roles */
            roles: components["schemas"]["Role"][];
            teams: components["schemas"]["Teams"] | null;
        };
        /** AccountRow */
        AccountRow: {
            /**
             * Account State
             * @enum {string}
             */
            account_state: "active" | "no_sign_in" | "disabled" | "erased";
            /** Category */
            category: string | null;
            /** Category Label */
            category_label: string | null;
            /** Disabled Reason */
            disabled_reason: string | null;
            /** Email */
            email: string | null;
            /** Forum Username */
            forum_username: string | null;
            /** Id */
            id: number;
            /**
             * Membership
             * @enum {string}
             */
            membership: "active" | "ending" | "pending" | "failed" | "ended" | "none";
            /** Membership Until */
            membership_until: string | null;
            /** Name */
            name: string | null;
            /** Old Forum */
            old_forum: ("unclaimed" | "reconnected") | null;
            /** Old Forum Username */
            old_forum_username: string | null;
            /** Roles */
            roles: components["schemas"]["Role"][];
            /** Year Group */
            year_group: string | null;
        };
        /**
         * Actions
         * @description What the person looking may do to this account, by the same checks the actions run.
         */
        Actions: {
            /** Correct Email */
            correct_email: boolean;
            /** Erase */
            erase: boolean;
            /** Export Data */
            export_data: boolean;
            /** Manage Access */
            manage_access: boolean;
            /** Picture Replacement */
            picture_replacement: boolean;
            /** Reconnect */
            reconnect: boolean;
            /** Resync Forum */
            resync_forum: boolean;
            /** Sync Billing */
            sync_billing: boolean;
        };
        /** Activity */
        Activity: {
            /** At */
            at: string;
            /** Category */
            category: string;
            /** Event Type */
            event_type: string;
            /** Id */
            id: number;
            /** Target */
            target: string | null;
        };
        /**
         * Attention
         * @description ``None`` for a kind the person may not act on, so the page does not offer it.
         */
        Attention: {
            /** Health Problems */
            health_problems: string[] | null;
            name_changes: components["schemas"]["aeronautics_members__api__admin_dashboard__Waiting"] | null;
            pictures: components["schemas"]["aeronautics_members__api__admin_dashboard__Waiting"] | null;
            sync_problems: components["schemas"]["aeronautics_members__api__admin_dashboard__Waiting"] | null;
        };
        /** BillingSyncOut */
        BillingSyncOut: {
            /** Changed */
            changed: boolean;
            /** Forum Error */
            forum_error: string | null;
        };
        /** Candidate */
        Candidate: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string | null;
            /** Id */
            id: number;
            /** Likely Because */
            likely_because: ("address" | "name") | null;
            /** Posts */
            posts: number | null;
            /** Username */
            username: string;
            /** Year Group */
            year_group: string | null;
        };
        /** CandidatesOut */
        CandidatesOut: {
            /** Items */
            items: components["schemas"]["Candidate"][];
            /** Likely */
            likely: boolean;
        };
        /** CandidatesQuery */
        CandidatesQuery: {
            /**
             * Q
             * @description Old username, name or address; none for the likely ones.
             * @default
             */
            q?: string;
        };
        /** Change */
        Change: {
            /** Current */
            current: string | null;
            /** Field */
            field: string;
            /** Label */
            label: string;
            /** Requested */
            requested: string | null;
        };
        /** ChangeApproveIn */
        ChangeApproveIn: {
            /**
             * Forum Username
             * @default null
             */
            forum_username?: string | null;
            /**
             * Note
             * @default null
             */
            note?: string | null;
        };
        /** ChangeApprovedOut */
        ChangeApprovedOut: {
            /** Forum Error */
            forum_error: string | null;
            /** Rename Pending */
            rename_pending: boolean;
        };
        /** ChangeRequest */
        ChangeRequest: {
            /** Changes */
            changes: components["schemas"]["Change"][];
            forum_username: components["schemas"]["ForumUsername"] | null;
            /** Is Name Change */
            is_name_change: boolean;
            /** Member Note */
            member_note: string | null;
            /** Requested Full Name */
            requested_full_name: string;
        };
        /** ChangedOut */
        ChangedOut: {
            /** Changed */
            changed: boolean;
        };
        /**
         * Counts
         * @description Numbers shown beside menu entries; 0 when there is nothing, or nothing the person may see.
         */
        Counts: {
            /** Reviews Waiting */
            reviews_waiting: number;
        };
        /** DashboardOut */
        DashboardOut: {
            attention: components["schemas"]["Attention"];
            /** Figures */
            figures: components["schemas"]["Figure"][];
            /** Recent Activity */
            recent_activity: components["schemas"]["Activity"][] | null;
        };
        /** DisabledIn */
        DisabledIn: {
            /** Disabled */
            disabled: boolean;
            /**
             * Reason
             * @default null
             */
            reason?: string | null;
        };
        /** EmailIn */
        EmailIn: {
            /** Email */
            email: string;
        };
        /** EmailOut */
        EmailOut: {
            /** Email */
            email: string;
        };
        /** EraseIn */
        EraseIn: {
            /** Confirm Email */
            confirm_email: string;
            /**
             * Reason
             * @default null
             */
            reason?: string | null;
        };
        /** EraseOut */
        EraseOut: {
            /** Forum Deferred */
            forum_deferred: boolean;
            /** Subscription Cancelled */
            subscription_cancelled: boolean;
        };
        /**
         * ErasureOut
         * @description What erasing this account would do, and what forbids it -- said before anybody confirms.
         */
        ErasureOut: {
            /** Blockers */
            blockers: string[];
            /** Confirm Email */
            confirm_email: string;
            /** Coverage End */
            coverage_end: string | null;
            /** Has Forum Account */
            has_forum_account: boolean;
            /** Has Stripe Customer */
            has_stripe_customer: boolean;
            /** Paid Periods */
            paid_periods: number;
            /** Subscription Active */
            subscription_active: boolean;
            /** Subscription Status */
            subscription_status: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /**
             * Details
             * @default null
             */
            details?: {
                [key: string]: unknown;
            } | null;
            /**
             * Fields
             * @default null
             */
            fields?: {
                [key: string]: string;
            } | null;
            /** Message */
            message: string;
        };
        /** ErrorOut */
        ErrorOut: {
            error: components["schemas"]["ErrorBody"];
        };
        /** Figure */
        Figure: {
            /**
             * Key
             * @enum {string}
             */
            key: "active" | "cancelled" | "forum" | "archive";
            /** Label */
            label: string;
            /** Link Url */
            link_url: string | null;
            /** Note */
            note: string;
            /** Value */
            value: number;
        };
        /** Forum */
        Forum: {
            /** Account State */
            account_state: string | null;
            cleanup: components["schemas"]["ForumCleanup"] | null;
            /** Error */
            error: string | null;
            /** Has Picture */
            has_picture: boolean;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Latest Picture */
            latest_picture: string | null;
            /** Review Note */
            review_note: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "disabled" | "no_membership" | "account_disabled" | "payment_processing" | "inactive_membership" | "active" | "reconnect_waiting" | "pending_avatar" | "rejected_avatar" | "needs_avatar";
            /** Status Label */
            status_label: string;
        };
        /**
         * ForumCleanup
         * @description The forum account a reconnect left behind, while it is not removed yet.
         */
        ForumCleanup: {
            /** Error */
            error: string | null;
            /** Failed */
            failed: boolean;
        };
        /** ForumResyncOut */
        ForumResyncOut: {
            /** Error */
            error: string | null;
        };
        /**
         * ForumUsername
         * @description Approving would make this the suggested forum username; the admin chooses.
         */
        ForumUsername: {
            /** Current */
            current: string;
            /** Suggested */
            suggested: string;
        };
        /** HistoryItem */
        HistoryItem: {
            /** At */
            at: string;
            /** By */
            by: string | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected" | "withdrawn";
            /** Id */
            id: number;
            /** Is Name Change */
            is_name_change: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "name_change" | "picture";
            /** Member Email */
            member_email: string | null;
            /** Requested Full Name */
            requested_full_name: string | null;
        };
        /** HistoryOut */
        HistoryOut: {
            /** Items */
            items: components["schemas"]["HistoryItem"][];
            /** Page */
            page: number;
            /** Pages */
            pages: number;
            /** Total */
            total: number;
        };
        /** HistoryQuery */
        HistoryQuery: {
            /**
             * Page
             * @default 1
             */
            page?: number;
        };
        /** MeOut */
        MeOut: {
            /** Admin Area */
            admin_area: boolean;
            /** Admin Notices */
            admin_notices: components["schemas"]["Notice"][];
            counts: components["schemas"]["Counts"];
            /** Email */
            email: string;
            /** First Name */
            first_name: string | null;
            /** Forum Username */
            forum_username: string | null;
            /** Id */
            id: number;
            /** Last Name */
            last_name: string | null;
            /** Permissions */
            permissions: ("accounts.billing" | "accounts.privacy" | "accounts.view" | "admin.access" | "approvals.review" | "forum.admin" | "forum.moderate" | "forum.moderator" | "logs.view" | "notifications.manage" | "notifications.receive" | "roles.manage" | "settings.credentials" | "settings.general" | "system.backup" | "system.update" | "teams.manage" | "teams.money")[];
            /** Roles */
            roles: string[];
            team_labels: components["schemas"]["TeamLabels"];
            /** Teams Area */
            teams_area: boolean;
        };
        /** Membership */
        Membership: {
            /** Category */
            category: string;
            /** Category Label */
            category_label: string;
            /** Email Private */
            email_private: string;
            /** Ends On */
            ends_on: string | null;
            /** First Name */
            first_name: string;
            /** Has Billing */
            has_billing: boolean;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name: string;
            /** Payment Status */
            payment_status: string;
            /** Payment Status Label */
            payment_status_label: string;
            /** Picture Replacement Allowed Since */
            picture_replacement_allowed_since: string | null;
            /** Renews On */
            renews_on: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "active" | "ending" | "pending" | "failed" | "ended" | "none";
            /** Title */
            title: string | null;
            /** Year Group */
            year_group: string | null;
        };
        /**
         * MembershipCounts
         * @description How many rows each membership filter shows, with the other filters as they are.
         */
        MembershipCounts: {
            /** Active */
            active: number;
            /** All */
            all: number;
            /** Ended */
            ended: number;
            /** Ending */
            ending: number;
            /** Failed */
            failed: number;
            /** None */
            none: number;
            /** Pending */
            pending: number;
        };
        /** NoteIn */
        NoteIn: {
            /**
             * Note
             * @default null
             */
            note?: string | null;
        };
        /**
         * Notice
         * @description A banner over every page of an area, for something that is off on purpose or by accident.
         */
        Notice: {
            /**
             * Link Label
             * @default null
             */
            link_label?: string | null;
            /**
             * Link Url
             * @default null
             */
            link_url?: string | null;
            /** Message */
            message: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "info" | "warning" | "danger";
        };
        /** OldForum */
        OldForum: {
            /** Claimed At */
            claimed_at: string | null;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string | null;
            /** Group */
            group: string | null;
            /** Group Reason */
            group_reason: string | null;
            /** Joined On */
            joined_on: string | null;
            /** Last Posted On */
            last_posted_on: string | null;
            /** Picture Url */
            picture_url: string | null;
            /** Posts */
            posts: number | null;
            /** Username */
            username: string;
            /** Year Group */
            year_group: string | null;
        };
        /**
         * Person
         * @description The member the item is about.
         */
        Person: {
            /** Email */
            email: string | null;
            /** Name */
            name: string;
            /** User Id */
            user_id: number | null;
        };
        /** Picture */
        Picture: {
            /** Forum Username */
            forum_username: string | null;
            /** Image Url */
            image_url: string | null;
        };
        /** PictureApprovedOut */
        PictureApprovedOut: {
            /** Forum Error */
            forum_error: string | null;
        };
        /** PictureReplacementIn */
        PictureReplacementIn: {
            /** Allow */
            allow: boolean;
        };
        /** PictureReplacementOut */
        PictureReplacementOut: {
            /** Allowed Since */
            allowed_since: string | null;
        };
        /** QueueItem */
        QueueItem: {
            /** At */
            at: string;
            change: components["schemas"]["ChangeRequest"] | null;
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "name_change" | "picture";
            person: components["schemas"]["Person"];
            picture: components["schemas"]["Picture"] | null;
        };
        /** ReconnectIn */
        ReconnectIn: {
            /** Profile Id */
            profile_id: number;
        };
        /** ReconnectOut */
        ReconnectOut: {
            /** Account Id */
            account_id: number;
            /**
             * Forum
             * @enum {string}
             */
            forum: "synced" | "background";
            /** Forum Error */
            forum_error: string | null;
            /** Old Username */
            old_username: string;
        };
        /** ReviewsOut */
        ReviewsOut: {
            /** Queue */
            queue: components["schemas"]["QueueItem"][];
            /** Sync Problems */
            sync_problems: components["schemas"]["SyncProblem"][] | null;
            waiting: components["schemas"]["aeronautics_members__api__admin_reviews__Waiting"];
        };
        /** Role */
        Role: {
            /** Label */
            label: string;
            /** Slug */
            slug: string;
        };
        /** RoleOption */
        RoleOption: {
            /** Covered By */
            covered_by: string | null;
            /** Description */
            description: string | null;
            /** Held */
            held: boolean;
            /** Label */
            label: string;
            /** Permissions */
            permissions: string[];
            /** Slug */
            slug: string;
        };
        /** RolesIn */
        RolesIn: {
            /** Roles */
            roles: string[];
        };
        /** RolesOut */
        RolesOut: {
            /** Changed */
            changed: boolean;
            /** Redundant */
            redundant: string[];
        };
        /** SessionOut */
        SessionOut: {
            /** Csrf Token */
            csrf_token: string;
            /** Signed In */
            signed_in: boolean;
        };
        /** SyncProblem */
        SyncProblem: {
            /** Email */
            email: string | null;
            /** Error */
            error: string | null;
            /** Last Synced At */
            last_synced_at: string | null;
            /** User Id */
            user_id: number | null;
        };
        /**
         * TeamLabels
         * @description What teams are called here; an admin can rename them.
         */
        TeamLabels: {
            /** Plural */
            plural: string;
            /** Singular */
            singular: string;
        };
        /** TeamMembership */
        TeamMembership: {
            /** End Reason Label */
            end_reason_label: string | null;
            /** Link Url */
            link_url: string | null;
            /** Since */
            since: string | null;
            /** Status Label */
            status_label: string;
            /** Team */
            team: string;
            /** Until */
            until: string | null;
        };
        /** TeamRole */
        TeamRole: {
            /** Role Label */
            role_label: string;
            /** Team */
            team: string;
        };
        /** Teams */
        Teams: {
            /** Memberships */
            memberships: components["schemas"]["TeamMembership"][];
            /** Roles */
            roles: components["schemas"]["TeamRole"][];
        };
        /**
         * Waiting
         * @description How many of one kind wait, and the oldest of them (for sync problems: the latest) in a few words.
         */
        aeronautics_members__api__admin_dashboard__Waiting: {
            /** At */
            at: string | null;
            /** Count */
            count: number;
            /** Summary */
            summary: string | null;
        };
        /**
         * Waiting
         * @description How much waits of each kind; ``None`` for a kind this person does not decide.
         */
        aeronautics_members__api__admin_reviews__Waiting: {
            /** Name Changes */
            name_changes: number | null;
            /** Pictures */
            pictures: number | null;
            /** Sync Problems */
            sync_problems: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_accounts: {
        parameters: {
            query?: {
                q?: string;
                membership?: "all" | "active" | "ending" | "pending" | "failed" | "ended" | "none";
                role?: string;
                account?: "all" | "active" | "no_sign_in" | "disabled" | "erased";
                kind?: "all" | "portal" | "archived";
                sort?: "name" | "kind" | "membership" | "until" | "forum";
                dir?: "asc" | "desc";
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListOut"];
                };
            };
            /** @description The input is not valid (see error.fields). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_account_billing_sync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingSyncOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not possible in the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_account_disabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisabledIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangedOut"];
                };
            };
            /** @description The input is not valid (see error.fields). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not possible in the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_account_email: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailOut"];
                };
            };
            /** @description The input is not valid (see error.fields). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not possible in the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_account_erase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EraseIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EraseOut"];
                };
            };
            /** @description The input is not valid (see error.fields). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not possible in the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_account_erasure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErasureOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_account_forum_resync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForumResyncOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not possible in the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_account_old_forum_candidates: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatesOut"];
                };
            };
            /** @description The input is not valid (see error.fields). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_account_picture_replacement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PictureReplacementIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PictureReplacementOut"];
                };
            };
            /** @description The input is not valid (see error.fields). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not possible in the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_account_reconnect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconnectIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconnectOut"];
                };
            };
            /** @description The input is not valid (see error.fields). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not possible in the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_account_roles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolesIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolesOut"];
                };
            };
            /** @description The input is not valid (see error.fields). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not possible in the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_reviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewsOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_reviews_history: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryOut"];
                };
            };
            /** @description The input is not valid (see error.fields). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_review_change_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeApproveIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeApprovedOut"];
                };
            };
            /** @description The input is not valid (see error.fields). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not possible in the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_review_change_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description Done. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The input is not valid (see error.fields). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not possible in the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_review_picture_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PictureApprovedOut"];
                };
            };
            /** @description The input is not valid (see error.fields). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not possible in the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_review_picture_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description Done. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The input is not valid (see error.fields). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Signed in, without the permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not possible in the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    session_state: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
}
